spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///tmp/{label}
#        git:
#          uri: https://github.com/threedr3am/share-project
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: env
server:
  port: 9988
